# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l7VC9dlaJPRq9YKYVrmR8aAqou2a8IWY
"""

class CellComponent(object):
    def __init__(self):
        pass
    
    def ReChanrge():
        pass

    def WasteEnergy():
        pass

class CellLeaf(CellComponent):    
    def __init__(self, wattage, energy):
        if energy < wattage:
            CellComponent.__init__(self)
            self.wattage = wattage
            self.energy = energy

    def ReCharge():
        #implement ReCharge từ interface CellComponent.
        #Nạp năng lượng cho cell.

    def WasteEnergy():
         #implement WasteEnergy từ interface CellComponent.
        #Thải năng lượng của Cell cho người dùng sử dụng.

class  BatteryComposite(CellComponent):
    def __init__(self, lstCell):
        CellComponent.__init__(self)
        self.lstCell = lstCell

    def ReCharge():
        #implement ReCharge từ interface CellComponent.
        #Nạp năng lượng cho tất cả các Cell có trong Battery.

    def WasteEnergy():
         #implement WasteEnergy từ interface CellComponent.
        #Thải năng lượng của các Cell trong Battery cho người dùng sử dụng.




def main():
    cell_1 = CellLeaf(5,3)
    cell_2 = CellLeaf(9,7)
    cell_3 = CellLeaf(15,12)
    listCell = [cell_1, cell_2, cell_3]
    battery = BatteryComposite(listCell)

    cell_1.ReChanrge()
    cell_1.WasteEnergy()

    battery.ReChanrge()
    battery.WasteEnergy()

"""# New Section"""